OTP redirect
DispuutHamers/webapp pull request #475
Opened 2022-09-04 20:13 UTC by koenjdejong

Nou dit werkt allemaal prima, totdat je echt gaat kijken waar nou daadwerkelijk voor ilid? gecheckt wordt. 
Dit geldt voor zowel de blogposts, bier en nog een paar anderen waar een exception op ilid? en dus indirect logged_in zit, die ik niet echt kan verklaren. Zo krijg je bijvoorbeeld ook als je naar users/new/ gaat als je uitgelogd bent een 500. 
De enige uitzondering hier momenteel is de homepage, want die geeft je direct de signin page, maar called niet logged_in.

Is hier een reden voor of zal ik alles binnenkort maar even veranderen?

Achja, dit is alvast een begin voor veel pagina's die wel achter de logged_in zitten en dus geredirect zullen worden.

Closes #474

2022-09-04 20:19 UTC, koenjdejong commented
Ai daar ga je al die tests failen nu 🥲

2022-09-17 20:46 UTC, koenjdejong commented
> Nou dit werkt allemaal prima, totdat je echt gaat kijken waar nou daadwerkelijk voor ilid? gecheckt wordt. Dit geldt voor zowel de blogposts, bier en nog een paar anderen waar een exception op ilid? en dus indirect logged_in zit, die ik niet echt kan verklaren. Zo krijg je bijvoorbeeld ook als je naar users/new/ gaat als je uitgelogd bent een 500. De enige uitzondering hier momenteel is de homepage, want die geeft je direct de signin page, maar called niet logged_in.
> 
> Is hier een reden voor of zal ik alles binnenkort maar even veranderen?
> 
> Achja, dit is alvast een begin voor veel pagina's die wel achter de logged_in zitten en dus geredirect zullen worden.
> 
> Closes #474

Dit is trouwens wel allemaal prima, was vergeten dat blogposts & beers ook publiek beschikbaar zijn.

2023-08-28 09:00 UTC, jackozi requested changes

2023-09-04 09:36 UTC, jackozi approved these changes

2023-09-06 09:37 UTC, merged