You cannot add your own chugs
DispuutHamers/webapp pull request #482
Opened 2022-09-17 16:49 UTC by koenjdejong

Closes #480

2022-09-17 17:22 UTC, dexbleeker commented
Very good idea! Maybe also do this for quotes?

2022-09-18 06:50 UTC, jackozi requested changes
Je kan dit volgens mij beter oplossen met een validation op de model. Dan is er ook nooit ergens anders waar het wel mis kan gaan.

2022-09-18 18:34 UTC, koenjdejong commented
> Je kan dit volgens mij beter oplossen met een validation op de model. Dan is er ook nooit ergens anders waar het wel mis kan gaan.

Probleem waar ik dan mee zit is hoe ik de current_user krijg in chug.rb, waar ik geen reporter heb zoals in quote. 
Er wordt namelijk *nog* niks meegestuurd als reporter.

2022-09-20 13:38 UTC, jackozi commented
> > Je kan dit volgens mij beter oplossen met een validation op de model. Dan is er ook nooit ergens anders waar het wel mis kan gaan.
> 
> Probleem waar ik dan mee zit is hoe ik de current_user krijg in chug.rb, waar ik geen reporter heb zoals in quote. Er wordt namelijk _nog_ niks meegestuurd als reporter.

Wat je zou kunnen doen is een attr_reader op de model zetten en dan meesturen via een hidden field, of wel de reporter gaan bijhouden zoals in quotes. Is misschien later ook handig voor auditing purposes als iemand een net iets te snelle tijd neerzet.

2022-09-20 14:02 UTC, koenjdejong commented
> > > Je kan dit volgens mij beter oplossen met een validation op de model. Dan is er ook nooit ergens anders waar het wel mis kan gaan.
> > 
> > 
> > Probleem waar ik dan mee zit is hoe ik de current_user krijg in chug.rb, waar ik geen reporter heb zoals in quote. Er wordt namelijk _nog_ niks meegestuurd als reporter.
> 
> Wat je zou kunnen doen is een attr_reader op de model zetten en dan meesturen via een hidden field, of wel de reporter gaan bijhouden zoals in quotes. Is misschien later ook handig voor auditing purposes als iemand een net iets te snelle tijd neerzet.

Reporter bijhouden is inderdaad een goed idee, kijk ik later even naar

2022-10-27 10:28 UTC, jackozi approved these changes

2022-10-27 13:54 UTC, merged