Auto signup the user
DispuutHamers/webapp pull request #497
Opened 2022-10-24 12:30 UTC by koenjdejong

Closes #493

2022-10-27 10:29 UTC, jackozi requested changes

2022-10-27 10:29 UTC, jackozi commented on config/database.yml
> -  username: hamers
Dit hoort hier niet :)

2022-10-31 16:38 UTC, dexbleeker approved these changes

2022-10-31 18:17 UTC, jackozi approved these changes

2022-10-31 18:17 UTC, merged