Fix activities showing up with "time until" when they are in progress
DispuutHamers/webapp pull request #563
Opened 2023-07-04 12:35 UTC by LvanArkel

Text now shows "Activiteit is bezig" when an activity is currently in progress.

2023-07-04 12:39 UTC, dexbleeker requested changes

2023-07-04 12:54 UTC, dexbleeker commented
@LvanArkel please do not force push. Now it is not a problem but in larger PR's this leads to having to review everything again, instead of the changes since the previous review.

2023-07-04 13:00 UTC, dexbleeker commented on app/views/shared/_next_event.html.erb
> +    <% end %>
Not sure if this works, but it is probably neater to do it inline and not redefine the styling:
```suggestion
    <h3 class="text-gray-600">
      <%= @next_event.past ? "Activiteit is bezig" : "Over #{time_ago_in_words(@next_event.date)}" %>
    </h3>
```

2023-09-13 08:06 UTC, dexbleeker approved these changes

2023-09-13 08:16 UTC, jackozi approved these changes

2023-09-13 08:44 UTC, merged